PAYLOAD_VERSION_V1 = 1
PAYLOAD_SCHEMA_TWIST_V1 = 'ros2_pqc.twist.v1'

SIG_SCHEME_UNKNOWN = 0
SIG_SCHEME_ML_DSA_44 = 1

HASH_SCHEME_UNKNOWN = 0
HASH_SCHEME_SHA256 = 1

RESULT_OK = 0
RESULT_SCHEMA_ERROR = 1
RESULT_ALG_UNSUPPORTED = 2
RESULT_DIGEST_MISMATCH = 3
RESULT_SIG_INVALID = 4
RESULT_REPLAY = 5
RESULT_EXPIRED = 6
RESULT_KEY_NOT_TRUSTED = 7
RESULT_INTERNAL_ERROR = 8

SIG_SCHEME_NAME_TO_ID = {
    'ML_DSA_44': SIG_SCHEME_ML_DSA_44,
    'ML-DSA-44': SIG_SCHEME_ML_DSA_44,
}
